// apps/web-svelte/src/lib/components/notes/note-list.svelte
<script lang="ts">
  import { Pin } from 'lucide-svelte';
  import { formatDistanceToNow } from 'date-fns';
  import type { Note } from '$lib/types';
  import TagPill from '$lib/components/tags/tag-pill.svelte';

  interface Props {
    notes: Note[];
    selectedId: string | null;
    onselect: (id: string) => void;
    onmoveNote?: (noteId: string, folderId: string | null) => Promise<void>;
  }

  let { notes, selectedId, onselect, onmoveNote }: Props = $props();

  /** Extracts the first non-empty line of content as a preview snippet. */
  function getContentPreview(content: string): string {
    const firstLine = content
      .split('\n')
      .map((line) => line.replace(/^#+\s*/, '').trim())
      .find((line) => line.length > 0);
    if (!firstLine) return 'No additional text';
    return firstLine.length > 80 ? firstLine.slice(0, 80) + '...' : firstLine;
  }

  /** Formats a date string as a relative time (e.g. "2 hours ago"). */
  function formatDate(dateString: string): string {
    try {
      return formatDistanceToNow(new Date(dateString), { addSuffix: true });
    } catch {
      return '';
    }
  }

  const sortedNotes = $derived(
    [...notes].sort((a, b) => {
      if (a.is_pinned && !b.is_pinned) return -1;
      if (!a.is_pinned && b.is_pinned) return 1;
      return new Date(b.updated_at).getTime() - new Date(a.updated_at).getTime();
    })
  );

  function handleDragStart(e: DragEvent, noteId: string) {
    e.dataTransfer?.setData('noteId', noteId);
    if (e.dataTransfer) e.dataTransfer.effectAllowed = 'move';
  }
</script>

{#if !sortedNotes?.length}
  <div class="flex items-center justify-center h-full text-muted text-sm">No notes yet</div>
{:else}
  <div class="overflow-y-auto h-full">
    {#each sortedNotes as note (note.id)}
      {@const isSelected = note.id === selectedId}
      <button
        onclick={() => onselect(note.id)}
        draggable={!!onmoveNote}
        ondragstart={(e) => handleDragStart(e, note.id)}
        class="w-full text-left px-4 py-3 border-b border-border transition-colors cursor-pointer
          {isSelected
            ? 'bg-accent/10 border-l-2 border-l-accent'
            : 'hover:bg-sidebar border-l-2 border-l-transparent'}"
      >
        <div class="flex items-center gap-1.5 mb-1">
          {#if note.is_pinned}
            <Pin class="w-3 h-3 text-accent shrink-0" />
          {/if}
          <span class="font-medium text-sm text-foreground truncate">{note.title || 'Untitled'}</span>
        </div>
        <p class="text-xs text-muted truncate mb-1">{getContentPreview(note.content)}</p>
        {#if note.tags && note.tags.length > 0}
          <div class="flex flex-wrap gap-1 mb-1">
            {#each note.tags.slice(0, 3) as tag (tag.id)}
              <TagPill name={tag.name} color={tag.color} size="sm" />
            {/each}
            {#if note.tags.length > 3}
              <span class="text-[10px] text-muted/70">+{note.tags.length - 3} more</span>
            {/if}
          </div>
        {/if}
        <span class="text-[11px] text-muted/70">{formatDate(note.updated_at)}</span>
      </button>
    {/each}
  </div>
{/if}

// apps/web/src/components/notes/note-list.tsx
'use client'

import { Pin } from 'lucide-react'
import { formatDistanceToNow } from 'date-fns'
import type { Note } from '@/lib/types'
import { TagPill } from '@/components/tags/tag-pill'

interface NoteListProps {
  notes: Note[]
  selectedId: string | null
  onSelect: (id: string) => void
  onMoveNote?: (noteId: string, folderId: string | null) => Promise<void>
}

/** Extracts the first non-empty line of content as a preview snippet. */
function getContentPreview(content: string): string {
  const firstLine = content
    .split('\n')
    .map(line => line.replace(/^#+\s*/, '').trim())
    .find(line => line.length > 0)
  if (!firstLine) return 'No additional text'
  return firstLine.length > 80 ? firstLine.slice(0, 80) + '...' : firstLine
}

/** Formats a date string as a relative time (e.g. "2 hours ago"). */
function formatDate(dateString: string): string {
  try {
    return formatDistanceToNow(new Date(dateString), { addSuffix: true })
  } catch {
    return ''
  }
}

/**
 * Scrollable list of note items sorted with pinned notes first.
 * Each item shows title, content preview, and relative date.
 * Supports drag-and-drop to move notes to folders.
 */
export function NoteList({ notes, selectedId, onSelect, onMoveNote }: NoteListProps) {
  // Sort: pinned first, then by updated_at descending
  const sortedNotes = [...notes].sort((a, b) => {
    if (a.is_pinned && !b.is_pinned) return -1
    if (!a.is_pinned && b.is_pinned) return 1
    return new Date(b.updated_at).getTime() - new Date(a.updated_at).getTime()
  })

  if (sortedNotes.length === 0) {
    return (
      <div className="flex items-center justify-center h-full text-muted text-sm">
        No notes yet
      </div>
    )
  }

  const handleDragStart = (e: React.DragEvent, noteId: string) => {
    e.dataTransfer.setData('noteId', noteId)
    e.dataTransfer.effectAllowed = 'move'
  }

  return (
    <div className="overflow-y-auto h-full">
      {sortedNotes.map(note => {
        const isSelected = note.id === selectedId
        return (
          <button
            key={note.id}
            onClick={() => onSelect(note.id)}
            draggable={!!onMoveNote}
            onDragStart={(e) => handleDragStart(e, note.id)}
            className={`
              w-full text-left px-4 py-3 border-b border-border
              transition-colors cursor-pointer
              ${isSelected
                ? 'bg-accent/10 border-l-2 border-l-accent'
                : 'hover:bg-sidebar border-l-2 border-l-transparent'
              }
            `}
          >
            <div className="flex items-center gap-1.5 mb-1">
              {note.is_pinned && (
                <Pin className="w-3 h-3 text-accent shrink-0" />
              )}
              <span className="font-medium text-sm text-foreground truncate">
                {note.title || 'Untitled'}
              </span>
            </div>
            <p className="text-xs text-muted truncate mb-1">
              {getContentPreview(note.content)}
            </p>
            {note.tags && note.tags.length > 0 && (
              <div className="flex flex-wrap gap-1 mb-1">
                {note.tags.slice(0, 3).map(tag => (
                  <TagPill key={tag.id} name={tag.name} color={tag.color} size="sm" />
                ))}
                {note.tags.length > 3 && (
                  <span className="text-[10px] text-muted/70">+{note.tags.length - 3} more</span>
                )}
              </div>
            )}
            <span className="text-[11px] text-muted/70">
              {formatDate(note.updated_at)}
            </span>
          </button>
        )
      })}
    </div>
  )
}
