// apps/web/src/components/layout/resizable-app-layout.tsx
'use client'

import { useCallback, useEffect, useState } from 'react'
import { AppSidebar } from './app-sidebar'
import { AppHeader } from './app-header'
import { ResizableDivider } from '@/components/ui/resizable-divider'

const SIDEBAR_WIDTH_KEY = 'notesapp-sidebar-width'
const DEFAULT_SIDEBAR_WIDTH = 256 // 64 * 4 = 256px (w-64)
const MIN_SIDEBAR_WIDTH = 200
const MAX_SIDEBAR_WIDTH = 400

interface ResizableAppLayoutProps {
  children: React.ReactNode
}

/**
 * Resizable app layout with sidebar, divider, and main content.
 * Sidebar width is persisted to localStorage.
 */
export function ResizableAppLayout({ children }: ResizableAppLayoutProps) {
  const [sidebarWidth, setSidebarWidth] = useState(DEFAULT_SIDEBAR_WIDTH)

  // Load from localStorage after mount to avoid hydration mismatch
  useEffect(() => {
    const saved = localStorage.getItem(SIDEBAR_WIDTH_KEY)
    if (saved) setSidebarWidth(parseInt(saved, 10))
  }, [])

  const handleSidebarResize = useCallback((newWidth: number) => {
    const clampedWidth = Math.max(MIN_SIDEBAR_WIDTH, Math.min(MAX_SIDEBAR_WIDTH, newWidth))
    setSidebarWidth(clampedWidth)
    localStorage.setItem(SIDEBAR_WIDTH_KEY, clampedWidth.toString())
  }, [])

  return (
    <div className="flex h-screen flex-col bg-background">
      {/* Mobile header with menu toggle */}
      <AppHeader />

      <div className="flex flex-1 overflow-hidden">
        {/* Desktop sidebar - hidden on mobile */}
        <div className="hidden lg:block" style={{ width: sidebarWidth }}>
          <AppSidebar />
        </div>

        {/* Resizable divider - hidden on mobile */}
        <div className="hidden lg:block">
          <ResizableDivider onResize={handleSidebarResize} />
        </div>

        {/* Main content area: note list + editor panes rendered by children */}
        <main className="flex flex-1 overflow-hidden">
          {children}
        </main>
      </div>
    </div>
  )
}

// apps/web-svelte/src/lib/components/layout/resizable-app-layout.svelte
<script lang="ts">
	/**
	 * Resizable app layout with sidebar, divider, and main content.
	 * Sidebar width is persisted to localStorage.
	 */
	import type { Snippet } from 'svelte';
	import AppSidebar from './app-sidebar.svelte';
	import AppHeader from './app-header.svelte';
	import ResizableDivider from '$lib/components/ui/resizable-divider.svelte';

	interface Props {
		children: Snippet;
	}

	let { children }: Props = $props();

	const SIDEBAR_WIDTH_KEY = 'notesapp-sidebar-width';
	const DEFAULT_SIDEBAR_WIDTH = 256;
	const MIN_SIDEBAR_WIDTH = 200;
	const MAX_SIDEBAR_WIDTH = 400;

	let sidebarWidth = $state(DEFAULT_SIDEBAR_WIDTH);

	// Load persisted width after mount
	$effect(() => {
		const saved = localStorage.getItem(SIDEBAR_WIDTH_KEY);
		if (saved) sidebarWidth = parseInt(saved, 10);
	});

	function handleSidebarResize(newWidth: number) {
		const clamped = Math.max(MIN_SIDEBAR_WIDTH, Math.min(MAX_SIDEBAR_WIDTH, newWidth));
		sidebarWidth = clamped;
		localStorage.setItem(SIDEBAR_WIDTH_KEY, clamped.toString());
	}
</script>

<div class="flex h-screen flex-col bg-background">
	<!-- Mobile header with menu toggle -->
	<AppHeader />

	<div class="flex flex-1 overflow-hidden">
		<!-- Desktop sidebar - hidden on mobile -->
		<div class="hidden lg:flex" style="width: {sidebarWidth}px;">
			<AppSidebar />
		</div>

		<!-- Resizable divider - hidden on mobile -->
		<ResizableDivider onresize={handleSidebarResize} class="hidden lg:block" />

		<!-- Main content: note list + editor panes -->
		<main class="flex flex-1 overflow-hidden">
			{@render children()}
		</main>
	</div>
</div>
