// apps/web/src/app/(app)/settings/page.tsx
'use client'

import { useEffect, useState } from 'react'
import { useRouter, useSearchParams } from 'next/navigation'
import {
  Settings,
  MessageCircle,
  Link,
  Unlink,
  Copy,
  Check,
  User,
  LogOut,
  Tag,
} from 'lucide-react'
import { useAuth } from '@/hooks/use-auth'
import { useTelegram } from '@/hooks/use-telegram'
import { useTags } from '@/hooks/use-tags'
import { TagManagementList } from '@/components/tags/tag-management-list'

/**
 * Settings page with Profile and Telegram Integration sections.
 */
export default function SettingsPage() {
  const router = useRouter()
  const searchParams = useSearchParams()
  const { user, loading: authLoading, signOut } = useAuth()
  const {
    status, loading: tgLoading, linkCode, botUsername, error,
    fetchStatus, linkTelegram, unlinkTelegram,
  } = useTelegram()
  const { tags, fetchTags, createTag, updateTag, deleteTag } = useTags()
  const [copied, setCopied] = useState(false)

  const activeTab = searchParams.get('tab') || 'profile'

  useEffect(() => {
    fetchStatus()
    fetchTags()
  }, [fetchStatus, fetchTags])

  const handleSignOut = async () => {
    await signOut()
    router.push('/login')
  }

  const handleCopyCode = async () => {
    if (!linkCode) return
    try {
      await navigator.clipboard.writeText(`/start ${linkCode}`)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      // Clipboard API may fail in some contexts
    }
  }

  const handleCreateTag = async (name: string, color: string) => {
    const tag = await createTag({ name, color })
    if (tag) await fetchTags()
    return tag
  }

  const handleUpdateTag = async (id: string, name: string, color: string) => {
    const tag = await updateTag(id, { name, color })
    if (tag) await fetchTags()
    return tag
  }

  const handleDeleteTag = async (id: string) => {
    const success = await deleteTag(id)
    if (success) await fetchTags()
    return success
  }

  return (
    <div className="flex-1 overflow-y-auto bg-background p-6 md:p-10">
      <div className="mx-auto max-w-2xl space-y-8">
        {/* Page header */}
        <div className="flex items-center gap-3">
          <Settings className="h-6 w-6 text-muted" />
          <h1 className="text-2xl font-bold text-foreground">Settings</h1>
        </div>

        {/* Tab navigation */}
        <nav className="flex gap-4 border-b border-border">
          <button
            onClick={() => router.push('/settings')}
            className={`pb-2 px-1 text-sm font-medium transition-colors ${
              activeTab === 'profile'
                ? 'border-b-2 border-accent text-accent'
                : 'text-muted hover:text-foreground'
            }`}
          >
            Profile
          </button>
          <button
            onClick={() => router.push('/settings?tab=tags')}
            className={`pb-2 px-1 text-sm font-medium transition-colors ${
              activeTab === 'tags'
                ? 'border-b-2 border-accent text-accent'
                : 'text-muted hover:text-foreground'
            }`}
          >
            Tags
          </button>
          <button
            onClick={() => router.push('/settings?tab=telegram')}
            className={`pb-2 px-1 text-sm font-medium transition-colors ${
              activeTab === 'telegram'
                ? 'border-b-2 border-accent text-accent'
                : 'text-muted hover:text-foreground'
            }`}
          >
            Telegram
          </button>
        </nav>

        {/* Profile section */}
        {activeTab === 'profile' && (
        <section className="rounded-xl border border-border bg-sidebar p-6">
          <div className="mb-4 flex items-center gap-2">
            <User className="h-5 w-5 text-muted" />
            <h2 className="text-lg font-semibold text-foreground">Profile</h2>
          </div>

          <div className="space-y-4">
            <div>
              <label className="text-xs font-medium uppercase tracking-wider text-muted">
                Email
              </label>
              <p className="mt-1 text-sm text-foreground">
                {authLoading ? 'Loading...' : user?.email ?? 'Unknown'}
              </p>
            </div>

            <div className="flex flex-wrap gap-3 pt-2">
              <button
                type="button"
                onClick={handleSignOut}
                className="inline-flex items-center gap-2 rounded-lg border border-border px-4 py-2 text-sm font-medium text-foreground transition-colors hover:bg-zinc-800"
              >
                <LogOut className="h-4 w-4" />
                Sign Out
              </button>
              <button
                type="button"
                disabled
                className="inline-flex items-center gap-2 rounded-lg border border-border px-4 py-2 text-sm font-medium text-muted opacity-50 cursor-not-allowed"
              >
                Change Password
              </button>
            </div>
          </div>
        </section>
        )}

        {/* Tags section */}
        {activeTab === 'tags' && (
        <section className="rounded-xl border border-border bg-sidebar p-6">
          <div className="mb-4 flex items-center gap-2">
            <Tag className="h-5 w-5 text-muted" />
            <h2 className="text-lg font-semibold text-foreground">Tags</h2>
          </div>
          <TagManagementList
            tags={tags}
            onCreate={handleCreateTag}
            onUpdate={handleUpdateTag}
            onDelete={handleDeleteTag}
          />
        </section>
        )}

        {/* Telegram integration section */}
        {activeTab === 'telegram' && (
        <section className="rounded-xl border border-border bg-sidebar p-6">
          <div className="mb-4 flex items-center gap-2">
            <MessageCircle className="h-5 w-5 text-muted" />
            <h2 className="text-lg font-semibold text-foreground">
              Telegram Integration
            </h2>
          </div>

          {error && (
            <p className="mb-4 rounded-lg bg-red-900/30 px-4 py-2 text-sm text-red-400">
              {error}
            </p>
          )}

          {/* Connected state */}
          {status?.is_linked && (
            <div className="space-y-4">
              <div className="flex items-center gap-2 text-sm text-green-400">
                <Link className="h-4 w-4" />
                <span>Connected</span>
              </div>
              {status.bot_linked_at && (
                <p className="text-xs text-muted">
                  Linked on{' '}
                  {new Date(status.bot_linked_at).toLocaleDateString(undefined, {
                    year: 'numeric', month: 'long', day: 'numeric',
                  })}
                </p>
              )}
              <button
                type="button"
                onClick={unlinkTelegram}
                disabled={tgLoading}
                className="inline-flex items-center gap-2 rounded-lg border border-red-800 px-4 py-2 text-sm font-medium text-red-400 transition-colors hover:bg-red-900/30 disabled:opacity-50"
              >
                <Unlink className="h-4 w-4" />
                {tgLoading ? 'Disconnecting...' : 'Disconnect'}
              </button>
            </div>
          )}

          {/* Not connected, no link code yet */}
          {!status?.is_linked && !linkCode && (
            <div className="space-y-3">
              <p className="text-sm text-muted">
                Connect Telegram to receive note reminders and manage todos from
                your phone.
              </p>
              <button
                type="button"
                onClick={linkTelegram}
                disabled={tgLoading}
                className="inline-flex items-center gap-2 rounded-lg bg-accent px-4 py-2 text-sm font-semibold text-black transition-opacity hover:opacity-90 disabled:opacity-50"
              >
                <Link className="h-4 w-4" />
                {tgLoading ? 'Generating...' : 'Connect Telegram'}
              </button>
            </div>
          )}

          {/* Link code displayed */}
          {!status?.is_linked && linkCode && botUsername && (
            <div className="space-y-4">
              <p className="text-sm text-muted">
                Send the following command to{' '}
                <span className="font-semibold text-foreground">
                  @{botUsername}
                </span>{' '}
                on Telegram:
              </p>
              <div className="flex items-center gap-2 rounded-lg border border-border bg-background px-4 py-3">
                <code className="flex-1 font-mono text-sm text-accent">
                  /start {linkCode}
                </code>
                <button
                  type="button"
                  onClick={handleCopyCode}
                  className="shrink-0 rounded-md p-1.5 text-muted transition-colors hover:bg-zinc-800 hover:text-foreground"
                  title="Copy command"
                >
                  {copied ? (
                    <Check className="h-4 w-4 text-green-400" />
                  ) : (
                    <Copy className="h-4 w-4" />
                  )}
                </button>
              </div>
              <p className="text-xs text-muted">
                After sending the command, refresh this page to confirm the
                connection.
              </p>
            </div>
          )}
        </section>
        )}
      </div>
    </div>
  )
}

// apps/web-svelte/src/routes/(app)/settings/+page.svelte
<script lang="ts">
	/**
	 * Settings page - tabbed interface.
	 * URL param: ?tab=account|tags|telegram|about
	 */
	import { page } from '$app/stores';
	import { goto } from '$app/navigation';
	import { onMount } from 'svelte';
	import { authStore } from '$lib/stores/auth-store.svelte';
	import { TagsStore } from '$lib/stores/tags-store.svelte';
	import TagManagementList from '$lib/components/tags/tag-management-list.svelte';
	import TelegramSettings from '$lib/components/settings/telegram-settings.svelte';
	import type { Tag } from '$lib/types';

	const tagsStore = new TagsStore();

	type Tab = 'account' | 'tags' | 'telegram' | 'about';

	const TABS: { value: Tab; label: string }[] = [
		{ value: 'account', label: 'Account' },
		{ value: 'tags', label: 'Tags' },
		{ value: 'telegram', label: 'Telegram' },
		{ value: 'about', label: 'About' }
	];

	const activeTab = $derived<Tab>(
		($page.url.searchParams.get('tab') as Tab) ?? 'account'
	);

	onMount(() => {
		tagsStore.fetchTags();
	});

	function setTab(tab: Tab) {
		goto(`?tab=${tab}`, { replaceState: true });
	}

	async function handleSignOut() {
		await authStore.signOut();
		goto('/login');
	}

	async function handleCreateTag(name: string, color: string): Promise<Tag | null> {
		try {
			return await tagsStore.createTag(name, color);
		} catch {
			return null;
		}
	}

	async function handleUpdateTag(id: string, name: string, color: string): Promise<Tag | null> {
		try {
			return await tagsStore.updateTag(id, { name, color });
		} catch {
			return null;
		}
	}

	async function handleDeleteTag(id: string): Promise<boolean> {
		try {
			await tagsStore.deleteTag(id);
			return true;
		} catch {
			return false;
		}
	}
</script>

<svelte:head>
	<title>Settings - NotesApp</title>
</svelte:head>

<div class="flex h-full w-full flex-col overflow-hidden">
	<!-- Tab bar -->
	<div class="flex items-center gap-1 border-b border-border px-4 py-2">
		{#each TABS as tab (tab.value)}
			<button
				onclick={() => setTab(tab.value)}
				class="rounded-md px-3 py-1 text-sm transition-colors {activeTab === tab.value
					? 'bg-accent/15 font-medium text-accent'
					: 'text-muted hover:text-foreground'}"
			>
				{tab.label}
			</button>
		{/each}
	</div>

	<!-- Tab content -->
	<div class="flex-1 overflow-y-auto p-6">
		{#if activeTab === 'account'}
			<div class="max-w-md space-y-6">
				<h2 class="text-lg font-semibold text-foreground">Account</h2>

				<div class="rounded-lg border border-border bg-sidebar p-4">
					{#if authStore.loading}
						<p class="text-sm text-muted">Loading...</p>
					{:else if authStore.user}
						<p class="text-sm font-medium text-foreground">{authStore.user.display_name}</p>
						<p class="mt-0.5 text-xs text-muted">Passkey authentication</p>
					{:else}
						<p class="text-sm text-muted">Not signed in</p>
					{/if}
				</div>

				<button
					onclick={handleSignOut}
					class="w-full rounded-lg border border-red-300 px-4 py-2 text-sm text-red-600 transition-colors hover:bg-red-50 dark:border-red-800 dark:hover:bg-red-900/20"
				>
					Sign Out
				</button>
			</div>

		{:else if activeTab === 'tags'}
			<div class="max-w-lg">
				<TagManagementList
					tags={tagsStore.tags}
					oncreate={handleCreateTag}
					onupdate={handleUpdateTag}
					ondelete={handleDeleteTag}
				/>
			</div>

		{:else if activeTab === 'telegram'}
			<div class="max-w-md">
				<TelegramSettings />
			</div>

		{:else if activeTab === 'about'}
			<div class="max-w-md space-y-4">
				<h2 class="text-lg font-semibold text-foreground">About</h2>
				<div class="rounded-lg border border-border bg-sidebar p-4 space-y-2">
					<div class="flex items-center justify-between text-sm">
						<span class="text-muted">App</span>
						<span class="font-medium text-foreground">NotesApp</span>
					</div>
					<div class="flex items-center justify-between text-sm">
						<span class="text-muted">Version</span>
						<span class="font-medium text-foreground">1.0.0</span>
					</div>
					<div class="flex items-center justify-between text-sm">
						<span class="text-muted">Stack</span>
						<span class="font-medium text-foreground">SvelteKit + FastAPI</span>
					</div>
				</div>
			</div>
		{/if}
	</div>
</div>
