// apps/web-svelte/src/lib/components/folders/folder-context-menu.svelte
<script lang="ts">
  import { MoreHorizontal, Pencil, FolderPlus, Trash2 } from 'lucide-svelte';

  interface Props {
    show: boolean;
    onclose: () => void;
    onrename: () => void;
    onnewsubfolder: () => void;
    ondelete: () => void;
    /** Trigger button click handler passed from parent */
    ontriggerclick: (e: MouseEvent) => void;
  }

  let { show, onclose, onrename, onnewsubfolder, ondelete, ontriggerclick }: Props = $props();

  /** Close menu on outside click */
  function handleOutsideClick(node: HTMLElement) {
    function onClick(e: MouseEvent) {
      if (!node.contains(e.target as Node)) onclose();
    }
    document.addEventListener('mousedown', onClick);
    return { destroy() { document.removeEventListener('mousedown', onClick); } };
  }
</script>

<!-- Trigger button -->
<button
  type="button"
  onclick={ontriggerclick}
  class="opacity-0 group-hover:opacity-100 shrink-0 p-0.5 rounded hover:bg-zinc-700"
>
  <MoreHorizontal class="h-3.5 w-3.5" />
</button>

<!-- Dropdown menu -->
{#if show}
  <div
    use:handleOutsideClick
    class="absolute right-0 top-full mt-1 w-40 rounded-md bg-zinc-800 border border-zinc-700
      shadow-lg z-10 py-1"
  >
    <button
      onclick={(e) => { e.stopPropagation(); onrename(); onclose(); }}
      class="w-full flex items-center gap-2 px-3 py-1.5 text-xs text-zinc-300 hover:bg-zinc-700 text-left"
    >
      <Pencil class="h-3 w-3" />
      Rename
    </button>
    <button
      onclick={(e) => { e.stopPropagation(); onnewsubfolder(); onclose(); }}
      class="w-full flex items-center gap-2 px-3 py-1.5 text-xs text-zinc-300 hover:bg-zinc-700 text-left"
    >
      <FolderPlus class="h-3 w-3" />
      New Subfolder
    </button>
    <button
      onclick={(e) => { e.stopPropagation(); ondelete(); }}
      class="w-full flex items-center gap-2 px-3 py-1.5 text-xs text-red-400 hover:bg-zinc-700 text-left"
    >
      <Trash2 class="h-3 w-3" />
      Delete
    </button>
  </div>
{/if}

// apps/web/src/components/folders/folder-context-menu.tsx
'use client'

import { useRef, useEffect } from 'react'
import { MoreHorizontal, Pencil, FolderPlus, Trash2 } from 'lucide-react'

interface FolderContextMenuProps {
  show: boolean
  onClose: () => void
  onRename: () => void
  onNewSubfolder: () => void
  onDelete: () => void
}

/**
 * Context menu for folder actions (rename, new subfolder, delete).
 * Closes on outside click or menu item selection.
 */
export function FolderContextMenu({
  show,
  onClose,
  onRename,
  onNewSubfolder,
  onDelete,
}: FolderContextMenuProps) {
  const menuRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (!show) return
    const handleClickOutside = (e: MouseEvent) => {
      if (menuRef.current && !menuRef.current.contains(e.target as Node)) {
        onClose()
      }
    }
    document.addEventListener('mousedown', handleClickOutside)
    return () => document.removeEventListener('mousedown', handleClickOutside)
  }, [show, onClose])

  if (!show) return null

  return (
    <div
      ref={menuRef}
      className="absolute right-0 top-full mt-1 w-40 rounded-md bg-zinc-800 border border-zinc-700 shadow-lg z-10 py-1"
    >
      <button
        onClick={(e) => { e.stopPropagation(); onRename(); onClose() }}
        className="w-full flex items-center gap-2 px-3 py-1.5 text-xs text-zinc-300 hover:bg-zinc-700 text-left"
      >
        <Pencil className="h-3 w-3" />
        Rename
      </button>
      <button
        onClick={(e) => { e.stopPropagation(); onNewSubfolder(); onClose() }}
        className="w-full flex items-center gap-2 px-3 py-1.5 text-xs text-zinc-300 hover:bg-zinc-700 text-left"
      >
        <FolderPlus className="h-3 w-3" />
        New Subfolder
      </button>
      <button
        onClick={(e) => { e.stopPropagation(); onDelete() }}
        className="w-full flex items-center gap-2 px-3 py-1.5 text-xs text-red-400 hover:bg-zinc-700 text-left"
      >
        <Trash2 className="h-3 w-3" />
        Delete
      </button>
    </div>
  )
}

export function FolderMenuTrigger({
  onClick,
}: {
  onClick: (e: React.MouseEvent) => void
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className="opacity-0 group-hover:opacity-100 shrink-0 p-0.5 rounded hover:bg-zinc-700"
    >
      <MoreHorizontal className="h-3.5 w-3.5" />
    </button>
  )
}
