// apps/web-svelte/src/lib/components/folders/folder-tree-item.svelte
<script lang="ts">
  import { ChevronRight, ChevronDown, FolderIcon, FolderOpen } from 'lucide-svelte';
  import type { Folder } from '$lib/types';
  import FolderContextMenu from './folder-context-menu.svelte';
  import FolderTreeItemSelf from './folder-tree-item.svelte';

  interface Props {
    folder: Folder;
    depth: number;
    selectedFolderId: string | null;
    onselect: (id: string) => void;
    onrename: (id: string, name: string) => Promise<Folder>;
    ondelete: (id: string) => Promise<void>;
    oncreate: (name: string, parentId: string) => Promise<Folder>;
    onmoveNote?: (noteId: string, folderId: string | null) => Promise<void>;
  }

  let { folder, depth, selectedFolderId, onselect, onrename, ondelete, oncreate, onmoveNote }: Props = $props();

  let isExpanded = $state(false);
  let showMenu = $state(false);
  let isDragOver = $state(false);

  // Rename state — renameName is populated when editing starts, not at init
  let isRenaming = $state(false);
  let renameName = $state('');
  let renameInput = $state<HTMLInputElement | null>(null);

  // Create child state
  let isCreating = $state(false);
  let createName = $state('');
  let createInput = $state<HTMLInputElement | null>(null);

  const hasChildren = $derived(folder.children && folder.children.length > 0);
  const isSelected = $derived(folder.id === selectedFolderId);
  const paddingLeft = $derived(12 + depth * 16);

  // Focus rename input when renaming starts
  $effect(() => {
    if (isRenaming && renameInput) {
      renameInput.focus();
      renameInput.select();
    }
  });

  // Focus create input when creating starts
  $effect(() => {
    if (isCreating && createInput) {
      createInput.focus();
    }
  });

  async function submitRename() {
    const trimmed = renameName.trim();
    if (trimmed && trimmed !== folder.name) {
      try {
        await onrename(folder.id, trimmed);
      } catch {
        renameName = folder.name;
      }
    }
    isRenaming = false;
  }

  function handleRenameKeydown(e: KeyboardEvent) {
    if (e.key === 'Enter') submitRename();
    else if (e.key === 'Escape') { renameName = folder.name; isRenaming = false; }
  }

  async function submitCreate() {
    const trimmed = createName.trim();
    if (trimmed) {
      try {
        await oncreate(trimmed, folder.id);
        createName = '';
        isCreating = false;
        isExpanded = true;
      } catch { /* error handled in parent */ }
    }
  }

  function handleCreateKeydown(e: KeyboardEvent) {
    if (e.key === 'Enter') submitCreate();
    else if (e.key === 'Escape') { createName = ''; isCreating = false; }
  }

  async function handleDelete() {
    if (window.confirm(`Delete "${folder.name}" and all its subfolders and notes?`)) {
      await ondelete(folder.id);
    }
  }

  function handleDragOver(e: DragEvent) {
    if (!onmoveNote) return;
    e.preventDefault();
    e.stopPropagation();
    isDragOver = true;
  }

  function handleDragLeave(e: DragEvent) {
    e.preventDefault();
    e.stopPropagation();
    isDragOver = false;
  }

  async function handleDrop(e: DragEvent) {
    e.preventDefault();
    e.stopPropagation();
    isDragOver = false;
    if (!onmoveNote) return;
    const noteId = e.dataTransfer?.getData('noteId');
    if (noteId) {
      try { await onmoveNote(noteId, folder.id); } catch (err) { console.error('Failed to move note:', err); }
    }
  }
</script>

<div>
  <!-- Folder row -->
  <div
    style="padding-left: {paddingLeft}px"
    class="group flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-sm transition-colors cursor-pointer
      {isSelected ? 'bg-zinc-700/60 text-white' : 'text-zinc-400 hover:bg-zinc-800 hover:text-zinc-200'}
      {isDragOver ? 'ring-2 ring-yellow-500 bg-zinc-800' : ''}"
    onclick={() => onselect(folder.id)}
    ondragover={handleDragOver}
    ondragleave={handleDragLeave}
    ondrop={handleDrop}
    role="button"
    tabindex="0"
    onkeydown={(e) => e.key === 'Enter' && onselect(folder.id)}
  >
    {#if hasChildren}
      <button
        type="button"
        onclick={(e) => { e.stopPropagation(); isExpanded = !isExpanded; }}
        class="shrink-0 p-0.5 rounded hover:bg-zinc-700/50"
      >
        {#if isExpanded}
          <ChevronDown class="h-3.5 w-3.5" />
        {:else}
          <ChevronRight class="h-3.5 w-3.5" />
        {/if}
      </button>
    {/if}

    <span title={folder.name}>
      {#if isExpanded && hasChildren}
        <FolderOpen class="h-4 w-4 shrink-0 text-yellow-500" />
      {:else}
        <FolderIcon class="h-4 w-4 shrink-0 text-yellow-500" />
      {/if}
    </span>

    {#if isRenaming}
      <input
        bind:this={renameInput}
        type="text"
        bind:value={renameName}
        onblur={submitRename}
        onkeydown={handleRenameKeydown}
        onclick={(e) => e.stopPropagation()}
        class="flex-1 bg-zinc-800 border border-zinc-600 rounded px-1.5 py-0.5
          text-sm text-white outline-none focus:border-yellow-500"
      />
    {:else}
      <span class="flex-1 truncate">{folder.name}</span>
    {/if}

    <!-- Context menu (trigger + dropdown) -->
    <div class="relative">
      <FolderContextMenu
        show={showMenu}
        ontriggerclick={(e) => { e.stopPropagation(); showMenu = !showMenu; }}
        onclose={() => (showMenu = false)}
        onrename={() => { renameName = folder.name; isRenaming = true; }}
        onnewsubfolder={() => { isCreating = true; isExpanded = true; }}
        ondelete={handleDelete}
      />
    </div>
  </div>

  <!-- Recursive children -->
  {#if isExpanded && hasChildren}
    <div>
      {#each folder.children! as child (child.id)}
        <FolderTreeItemSelf
          folder={child}
          depth={depth + 1}
          {selectedFolderId}
          onselect={onselect}
          onrename={onrename}
          ondelete={ondelete}
          oncreate={oncreate}
          onmoveNote={onmoveNote}
        />
      {/each}
    </div>
  {/if}

  <!-- Child folder creation input -->
  {#if isCreating}
    <div style="padding-left: {paddingLeft + 16}px" class="flex items-center gap-1.5 px-3 py-1.5">
      <FolderIcon class="h-4 w-4 shrink-0 text-yellow-500" />
      <input
        bind:this={createInput}
        type="text"
        bind:value={createName}
        onblur={submitCreate}
        onkeydown={handleCreateKeydown}
        placeholder="Folder name"
        class="flex-1 bg-zinc-800 border border-zinc-600 rounded px-1.5 py-0.5
          text-sm text-white outline-none focus:border-yellow-500 placeholder:text-zinc-500"
      />
    </div>
  {/if}
</div>

// apps/web/src/components/folders/folder-tree-item.tsx
'use client'

import { useState, useRef, useEffect } from 'react'
import { ChevronRight, ChevronDown, FolderIcon, FolderOpen } from 'lucide-react'
import type { Folder } from '@/lib/types'
import { FolderContextMenu, FolderMenuTrigger } from './folder-context-menu'

interface FolderTreeItemProps {
  folder: Folder
  depth: number
  selectedFolderId: string | null
  onSelect: (id: string) => void
  onRename: (id: string, name: string) => Promise<Folder>
  onDelete: (id: string) => Promise<void>
  onCreate: (name: string, parentId: string) => Promise<Folder>
  onMoveNote?: (noteId: string, folderId: string | null) => Promise<void>
}

/** Hook for managing folder rename state and actions */
function useRename(folderId: string, initialName: string, onRename: (id: string, name: string) => Promise<Folder>) {
  const [isRenaming, setIsRenaming] = useState(false)
  const [name, setName] = useState(initialName)
  const inputRef = useRef<HTMLInputElement>(null)

  useEffect(() => {
    if (isRenaming && inputRef.current) {
      inputRef.current.focus()
      inputRef.current.select()
    }
  }, [isRenaming])

  const submit = async () => {
    const trimmed = name.trim()
    if (trimmed && trimmed !== initialName) {
      try {
        await onRename(folderId, trimmed)
      } catch {
        setName(initialName)
      }
    }
    setIsRenaming(false)
  }

  const onKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter') submit()
    else if (e.key === 'Escape') {
      setName(initialName)
      setIsRenaming(false)
    }
  }

  return { isRenaming, name, inputRef, setName, setIsRenaming, submit, onKeyDown }
}

/** Hook for creating child folder */
function useCreateChild(parentId: string, onCreate: (name: string, parentId: string) => Promise<Folder>) {
  const [isCreating, setIsCreating] = useState(false)
  const [name, setName] = useState('')
  const inputRef = useRef<HTMLInputElement>(null)

  useEffect(() => {
    if (isCreating && inputRef.current) inputRef.current.focus()
  }, [isCreating])

  const submit = async () => {
    const trimmed = name.trim()
    if (trimmed) {
      try {
        await onCreate(trimmed, parentId)
        setName('')
        setIsCreating(false)
        return true
      } catch {
        return false
      }
    }
    return false
  }

  const onKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter') submit()
    else if (e.key === 'Escape') {
      setName('')
      setIsCreating(false)
    }
  }

  return { isCreating, name, inputRef, setName, setIsCreating, submit, onKeyDown }
}

/**
 * Recursive folder tree item with expand/collapse, inline rename,
 * context menu (rename, new subfolder, delete), and nested children.
 */
export function FolderTreeItem({
  folder,
  depth,
  selectedFolderId,
  onSelect,
  onRename,
  onDelete,
  onCreate,
  onMoveNote,
}: FolderTreeItemProps) {
  const [isExpanded, setIsExpanded] = useState(false)
  const [showMenu, setShowMenu] = useState(false)
  const [isDragOver, setIsDragOver] = useState(false)

  const rename = useRename(folder.id, folder.name, onRename)
  const createChild = useCreateChild(folder.id, onCreate)

  const hasChildren = folder.children && folder.children.length > 0
  const isSelected = folder.id === selectedFolderId
  const paddingLeft = 12 + depth * 16

  const handleDelete = async () => {
    if (window.confirm(`Delete "${folder.name}" and all its subfolders and notes?`)) {
      await onDelete(folder.id)
    }
  }

  const handleCreateChild = async () => {
    const success = await createChild.submit()
    if (success) setIsExpanded(true)
  }

  const handleDragOver = (e: React.DragEvent) => {
    if (!onMoveNote) return
    e.preventDefault()
    e.stopPropagation()
    setIsDragOver(true)
  }

  const handleDragLeave = (e: React.DragEvent) => {
    e.preventDefault()
    e.stopPropagation()
    setIsDragOver(false)
  }

  const handleDrop = async (e: React.DragEvent) => {
    e.preventDefault()
    e.stopPropagation()
    setIsDragOver(false)

    if (!onMoveNote) return

    const noteId = e.dataTransfer.getData('noteId')
    if (noteId) {
      try {
        await onMoveNote(noteId, folder.id)
      } catch (error) {
        console.error('Failed to move note:', error)
      }
    }
  }

  return (
    <div>
      {/* Folder row */}
      <div
        style={{ paddingLeft: `${paddingLeft}px` }}
        className={`group flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-sm transition-colors cursor-pointer ${
          isSelected ? 'bg-zinc-700/60 text-white' : 'text-zinc-400 hover:bg-zinc-800 hover:text-zinc-200'
        } ${isDragOver ? 'ring-2 ring-yellow-500 bg-zinc-800' : ''}`}
        onClick={() => onSelect(folder.id)}
        onDragOver={handleDragOver}
        onDragLeave={handleDragLeave}
        onDrop={handleDrop}
      >
        {hasChildren && (
          <button
            type="button"
            onClick={(e) => { e.stopPropagation(); setIsExpanded(!isExpanded) }}
            className="shrink-0 p-0.5 rounded hover:bg-zinc-700/50"
          >
            {isExpanded ? <ChevronDown className="h-3.5 w-3.5" /> : <ChevronRight className="h-3.5 w-3.5" />}
          </button>
        )}

        <span title={folder.name}>
          {isExpanded && hasChildren ? (
            <FolderOpen className="h-4 w-4 shrink-0 text-yellow-500" />
          ) : (
            <FolderIcon className="h-4 w-4 shrink-0 text-yellow-500" />
          )}
        </span>

        {rename.isRenaming ? (
          <input
            ref={rename.inputRef}
            type="text"
            value={rename.name}
            onChange={(e) => rename.setName(e.target.value)}
            onBlur={rename.submit}
            onKeyDown={rename.onKeyDown}
            onClick={(e) => e.stopPropagation()}
            className="flex-1 bg-zinc-800 border border-zinc-600 rounded px-1.5 py-0.5 text-sm text-white outline-none focus:border-yellow-500"
          />
        ) : (
          <span className="flex-1 truncate">{folder.name}</span>
        )}

        <div className="relative">
          <FolderMenuTrigger onClick={(e) => { e.stopPropagation(); setShowMenu(!showMenu) }} />
          <FolderContextMenu
            show={showMenu}
            onClose={() => setShowMenu(false)}
            onRename={() => rename.setIsRenaming(true)}
            onNewSubfolder={() => { createChild.setIsCreating(true); setIsExpanded(true) }}
            onDelete={handleDelete}
          />
        </div>
      </div>

      {isExpanded && hasChildren && (
        <div>
          {folder.children!.map((child) => (
            <FolderTreeItem
              key={child.id}
              folder={child}
              depth={depth + 1}
              selectedFolderId={selectedFolderId}
              onSelect={onSelect}
              onRename={onRename}
              onDelete={onDelete}
              onCreate={onCreate}
              onMoveNote={onMoveNote}
            />
          ))}
        </div>
      )}

      {createChild.isCreating && (
        <div style={{ paddingLeft: `${paddingLeft + 16}px` }} className="flex items-center gap-1.5 px-3 py-1.5">
          <FolderIcon className="h-4 w-4 shrink-0 text-yellow-500" />
          <input
            ref={createChild.inputRef}
            type="text"
            value={createChild.name}
            onChange={(e) => createChild.setName(e.target.value)}
            onBlur={handleCreateChild}
            onKeyDown={createChild.onKeyDown}
            placeholder="Folder name"
            className="flex-1 bg-zinc-800 border border-zinc-600 rounded px-1.5 py-0.5 text-sm text-white outline-none focus:border-yellow-500 placeholder:text-zinc-500"
          />
        </div>
      )}
    </div>
  )
}
