// apps/web/src/app/(app)/todos/page.tsx
'use client'

import { useEffect, useState, useCallback, useMemo } from 'react'
import { useSearchParams } from 'next/navigation'
import { Search, AlertCircle } from 'lucide-react'
import { useTodos, type TodoFilter } from '@/hooks/use-todos'
import { TodoList } from '@/components/todos/todo-list'
import { TodoCreateForm } from '@/components/todos/todo-create-form'
import type { Todo } from '@/lib/types'

const FILTER_TABS: { label: string; value: TodoFilter }[] = [
  { label: 'All', value: 'all' },
  { label: 'Active', value: 'active' },
  { label: 'Completed', value: 'completed' },
  { label: 'Overdue', value: 'overdue' },
]

/**
 * Full-width todo list page with filter tabs, search, and inline creation.
 */
export default function TodosPage() {
  const searchParams = useSearchParams()
  const {
    todos, loading, error, filter,
    setFilter, fetchTodos, createTodo,
    updateTodo, deleteTodo, toggleTodo, reorderTodos,
  } = useTodos()

  const [search, setSearch] = useState('')
  const tagIdsParam = searchParams.get('tags')
  const tagIds = useMemo(
    () => (tagIdsParam ? tagIdsParam.split(',') : undefined),
    [tagIdsParam]
  )

  // Fetch todos on mount and when filter or tags change
  useEffect(() => {
    fetchTodos(filter, tagIds)
  }, [filter, tagIds, fetchTodos])

  const handleFilterChange = (newFilter: TodoFilter) => {
    setFilter(newFilter)
  }

  const handleCreated = useCallback(async (payload: Todo) => {
    // payload is raw form data cast as Todo; pass to createTodo
    await createTodo(payload as unknown as Parameters<typeof createTodo>[0])
  }, [createTodo])

  const handleUpdate = useCallback(async (id: string, data: Record<string, unknown>) => {
    // Special case: subtask creation forwarded from TodoItem
    if (id === '__create__') {
      await createTodo(data as unknown as Parameters<typeof createTodo>[0])
      return
    }
    await updateTodo(id, data)
  }, [updateTodo, createTodo])

  // Client-side search filtering
  const filtered = search.trim()
    ? todos.filter((t) => t.title.toLowerCase().includes(search.toLowerCase()))
    : todos

  return (
    <div className="mx-auto w-full max-w-3xl px-4 py-8">
      {/* Header */}
      <h1 className="text-2xl font-bold tracking-tight text-foreground">Todos</h1>

      {/* Search input */}
      <div className="relative mt-4">
        <Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted" />
        <input
          type="text"
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          placeholder="Search todos..."
          className="h-9 w-full rounded-md border border-border bg-background pl-9 pr-3
            text-sm text-foreground placeholder:text-muted
            focus:outline-none focus:ring-1 focus:ring-accent"
        />
      </div>

      {/* Filter tabs */}
      <div className="mt-4 flex gap-1 border-b border-border">
        {FILTER_TABS.map((tab) => (
          <button
            key={tab.value}
            onClick={() => handleFilterChange(tab.value)}
            className={`px-3 py-2 text-sm font-medium transition-colors
              ${filter === tab.value
                ? 'border-b-2 border-accent text-foreground'
                : 'text-muted hover:text-foreground'
              }`}
          >
            {tab.label}
          </button>
        ))}
      </div>

      {/* Create form */}
      <div className="mt-4">
        <TodoCreateForm onCreated={handleCreated} />
      </div>

      {/* Error message */}
      {error && (
        <div className="mt-4 flex items-center gap-2 rounded-md bg-red-500/10 px-3 py-2 text-sm text-red-500">
          <AlertCircle size={16} />
          {error}
        </div>
      )}

      {/* Loading state */}
      {loading && (
        <div className="mt-8 flex justify-center text-sm text-muted">Loading...</div>
      )}

      {/* Todo list */}
      {!loading && (
        <div className="mt-4">
          <TodoList
            todos={filtered}
            onToggle={toggleTodo}
            onUpdate={handleUpdate}
            onDelete={deleteTodo}
            onReorder={reorderTodos}
          />
        </div>
      )}
    </div>
  )
}

// apps/web-svelte/src/routes/(app)/todos/+page.svelte
<script lang="ts">
	/**
	 * Todos page - filterable list with create form.
	 * URL params: tags (comma-separated IDs), filter (all|active|completed|overdue).
	 */
	import { page } from '$app/stores';
	import { goto } from '$app/navigation';
	import { onMount } from 'svelte';
	import { TodosStore, type TodoFilter } from '$lib/stores/todos-store.svelte';
	import { tagsStore } from '$lib/stores/tags-store.svelte';
	import TodoList from '$lib/components/todos/todo-list.svelte';
	import TodoCreateForm from '$lib/components/todos/todo-create-form.svelte';
	import TagFilterSection from '$lib/components/tags/tag-filter-section.svelte';
	import { Filter } from 'lucide-svelte';
	import type { Todo } from '$lib/types';

	const todosStore = new TodosStore();
	let showTagFilter = $state(false);
	

	// Derive URL params reactively
	const tagParam = $derived($page.url.searchParams.get('tags') ?? '');
	const selectedTagIds = $derived(tagParam ? tagParam.split(',').filter(Boolean) : []);
	const activeFilter = $derived<TodoFilter>(
		($page.url.searchParams.get('filter') as TodoFilter) ?? 'all'
	);

	// Fetch todos when URL params change
	$effect(() => {
		todosStore.fetchTodos(activeFilter, selectedTagIds.length ? selectedTagIds : undefined);
	});

	onMount(() => {
		tagsStore.fetchTags();
	});

	const FILTERS: { value: TodoFilter; label: string }[] = [
		{ value: 'all', label: 'All' },
		{ value: 'active', label: 'Active' },
		{ value: 'completed', label: 'Done' },
		{ value: 'overdue', label: 'Overdue' }
	];

	function setFilter(filter: TodoFilter) {
		const params = new URLSearchParams($page.url.searchParams);
		if (filter === 'all') {
			params.delete('filter');
		} else {
			params.set('filter', filter);
		}
		goto(`?${params.toString()}`, { replaceState: true });
	}

	function toggleTag(tagId: string) {
		const params = new URLSearchParams($page.url.searchParams);
		const current = tagParam ? tagParam.split(',').filter(Boolean) : [];
		const next = current.includes(tagId)
			? current.filter((id) => id !== tagId)
			: [...current, tagId];
		if (next.length) {
			params.set('tags', next.join(','));
		} else {
			params.delete('tags');
		}
		goto(`?${params.toString()}`, { replaceState: true });
	}

	function clearTagFilters() {
		const params = new URLSearchParams($page.url.searchParams);
		params.delete('tags');
		goto(`?${params.toString()}`, { replaceState: true });
	}

	async function handleCreated(todo: Todo) {
		await todosStore.createTodo({
			title: todo.title,
			description: todo.description ?? undefined,
			priority: todo.priority,
			deadline: todo.deadline ?? undefined,
			parent_id: todo.parent_id ?? undefined,
			reminder_at: todo.reminder_at ?? undefined,
			recurrence_type: todo.recurrence_type ?? undefined,
			recurrence_interval: todo.recurrence_interval ?? undefined,
			recurrence_days: todo.recurrence_days ?? undefined,
			recurrence_end_date: todo.recurrence_end_date ?? undefined
		});
	}

	async function handleToggle(id: string) {
		await todosStore.toggleTodo(id);
	}

	async function handleUpdate(id: string, data: Record<string, unknown>) {
		// Handle subtask creation (special '__create__' id from todo-item)
		if (id === '__create__') {
			await todosStore.createTodo(data as unknown as Parameters<typeof todosStore.createTodo>[0]);
			return;
		}
		await todosStore.updateTodo(id, data);
	}

	async function handleDelete(id: string) {
		await todosStore.deleteTodo(id);
	}

	async function handleReorder(orderedIds: string[]) {
		await todosStore.reorderTodos(orderedIds);
	}
</script>

<svelte:head>
	<title>Todos - NotesApp</title>
</svelte:head>

<div class="flex h-full w-full flex-col overflow-hidden">
	<!-- Toolbar: filter tabs -->
	<div class="flex items-center gap-1 border-b border-border px-4 py-2">
		{#each FILTERS as f (f.value)}
			<button
				onclick={() => setFilter(f.value)}
				class="rounded-md px-3 py-1 text-sm transition-colors {activeFilter === f.value
					? 'bg-accent/15 font-medium text-accent'
					: 'text-muted hover:text-foreground'}"
			>
				{f.label}
			</button>
		{/each}

		<!-- Tag filter button -->
		<div class="relative ml-auto flex items-center gap-2">
			{#if selectedTagIds.length > 0}
				<button onclick={clearTagFilters} class="text-xs text-muted hover:text-foreground">
					Clear ({selectedTagIds.length})
				</button>
			{/if}
			<button
				onclick={() => (showTagFilter = !showTagFilter)}
				class="flex items-center gap-1 rounded-md px-2 py-1 text-sm {selectedTagIds.length > 0 ? 'bg-accent/15 text-accent' : 'text-muted hover:text-foreground'}"
			>
				<Filter class="h-3.5 w-3.5" />
				Tags
			</button>
			{#if showTagFilter}
				<div class="absolute right-0 top-full mt-1 z-50 w-48 bg-zinc-800 border border-zinc-700 rounded-lg shadow-lg p-2">
					<TagFilterSection
						tags={tagsStore.tags ?? []}
						selectedTagIds={selectedTagIds}
						ontoggleTag={toggleTag}
						onclearAll={clearTagFilters}
					/>
				</div>
			{/if}
		</div>
		<span class="text-xs text-muted">{todosStore.total} item{todosStore.total !== 1 ? 's' : ''}</span>
	</div>

	<!-- Main content -->
	<div class="flex-1 overflow-y-auto p-4">
		<div class="mb-4">
			<TodoCreateForm oncreated={handleCreated} />
		</div>

		{#if todosStore.error}
			<p class="mb-3 rounded-md bg-red-50 px-3 py-2 text-sm text-red-600 dark:bg-red-900/20 dark:text-red-400">
				{todosStore.error}
			</p>
		{/if}

		<TodoList
			todos={todosStore.todos}
			ontoggle={handleToggle}
			onupdate={handleUpdate}
			ondelete={handleDelete}
			onreorder={handleReorder}
		/>
	</div>
</div>
